CreateThread(function()
    DoScreenFadeOut(3000)
    Wait(3000)
    SetMaxWantedLevel(0)
    while (not NetworkIsSessionStarted()) do Wait(0) end
    ShutdownLoadingScreen()
    ShutdownLoadingScreenNui()
    local mod = GetHashKey("mp_m_freemode_01")
    RequestModel(mod)
    while not HasModelLoaded(mod) do Citizen.Wait(10) end
    SetPlayerModel(PlayerId(), mod)
    SetEntityCoords(PlayerPedId(), Config.spawnPosition.x, Config.spawnPosition.y, Config.spawnPosition.z, Config.spawnPosition.heading)
    DoScreenFadeIn(3000)
    FreezeEntityPosition(PlayerPedId(), false)
    NetworkConcealPlayer(NetworkGetPlayerIndexFromPed(PlayerPedId()), false, 1)
    SetPedDefaultComponentVariation(PlayerPedId())
    SetEntityVisible(PlayerPedId(), true)
    MainMenu()
end)