CreateThread(function()
    local safezoneBlip = AddBlipForCoord(Config.safezoneCenter.x, Config.safezoneCenter.y, Config.safezoneCenter.z)
    SetBlipSprite(safezoneBlip, 464)
    SetBlipDisplay(safezoneBlip, 4)
    SetBlipColour(safezoneBlip, 43)
    SetBlipAsShortRange(safezoneBlip, true)
    SetBlipScale(safezoneBlip, 1.0)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentString("Zone de sécurité")
    EndTextCommandSetBlipName(safezoneBlip)
    local safezoneRadiusBlip = AddBlipForRadius(Config.safezoneCenter.x, Config.safezoneCenter.y, Config.safezoneCenter.z, Config.safezoneRadius)
    SetBlipColour(safezoneRadiusBlip, 43)
    SetBlipAlpha(safezoneRadiusBlip, 128)
end)